### ISSUE TITLE
Error installing dependency 2.0.0

### ISSUE THREAD

**Issue by alex-rarzola** [mathiasbynens/unicode-match-property-ecmascript#1]
I am facing the following error message

**_npm ERR! notarget No matching version found for unicode-match-property-ecmascript@^2.0.0._**

the error appears when im trying to install the dependency

What would be reason of this error?

**Comment by mathiasbynens** [comment]
The latest published version is v2.0.0: https://www.npmjs.com/package/unicode-match-property-ecmascript Are you using some ancient version of `npm`?
